# version del compose que se quiere usar
version: "3.8"

services:
  backend:
    image: dhiguitaa/backend:v1
    ports:
      - "4001:4001"
  frontend:
    image: dhiguitaa/frontend:v2
    ports:
      - "5000:80"
    depends_on:
      - backend
